---
title: "lab18"
format: pdf
editor: visual
---

```{r echo=FALSE}
cdc <- data.frame(
                                 Year = c(1922L,1923L,1924L,1925L,
                                          1926L,1927L,1928L,1929L,1930L,1931L,
                                          1932L,1933L,1934L,1935L,1936L,
                                          1937L,1938L,1939L,1940L,1941L,1942L,
                                          1943L,1944L,1945L,1946L,1947L,
                                          1948L,1949L,1950L,1951L,1952L,
                                          1953L,1954L,1955L,1956L,1957L,1958L,
                                          1959L,1960L,1961L,1962L,1963L,
                                          1964L,1965L,1966L,1967L,1968L,1969L,
                                          1970L,1971L,1972L,1973L,1974L,
                                          1975L,1976L,1977L,1978L,1979L,1980L,
                                          1981L,1982L,1983L,1984L,1985L,
                                          1986L,1987L,1988L,1989L,1990L,
                                          1991L,1992L,1993L,1994L,1995L,1996L,
                                          1997L,1998L,1999L,2000L,2001L,
                                          2002L,2003L,2004L,2005L,2006L,2007L,
                                          2008L,2009L,2010L,2011L,2012L,
                                          2013L,2014L,2015L,2016L,2017L,2018L,
                                          2019L),
         Cases = c(107473,164191,165418,152003,
                                          202210,181411,161799,197371,
                                          166914,172559,215343,179135,265269,
                                          180518,147237,214652,227319,103188,
                                          183866,222202,191383,191890,109873,
                                          133792,109860,156517,74715,69479,
                                          120718,68687,45030,37129,60886,
                                          62786,31732,28295,32148,40005,
                                          14809,11468,17749,17135,13005,6799,
                                          7717,9718,4810,3285,4249,3036,
                                          3287,1759,2402,1738,1010,2177,2063,
                                          1623,1730,1248,1895,2463,2276,
                                          3589,4195,2823,3450,4157,4570,
                                          2719,4083,6586,4617,5137,7796,6564,
                                          7405,7298,7867,7580,9771,11647,
                                          25827,25616,15632,10454,13278,
                                          16858,27550,18719,48277,28639,32971,
                                          20762,17972,18975,15609,18617)
       )
```

```{r}
library(ggplot2)
base <- ggplot(cdc) +
  aes(Year,Cases) +
  geom_point() +
  geom_line() +
  scale_y_continuous(labels = scales::label_comma())
base
```
```{r}
base + geom_vline(xintercept=1946, col="blue", linetype=2) + 
  geom_vline(xintercept=1996, col="red", linetype=2)
```
```{r}
library(jsonlite)
subject <- read_json("http://cmi-pb.org/api/subject",simplifyVector = T)
```

```{r}
table(subject$race, subject$biological_sex)
```

```{r}
specimen <- read_json("http://cmi-pb.org/api/specimen",simplifyVector = T)
dim(specimen)
```

```{r}
library(dplyr)
meta <- inner_join(specimen,subject)
dim(subject)
dim(meta)
```

```{r}
titer <- read_json("http://cmi-pb.org/api/ab_titer",simplifyVector = T)
table(titer$isotype)
```
```{r}
abmeta <- inner_join(titer,meta)
head(abmeta)
```
```{r}
table(abmeta$visit)
```

```{r}
ig1 <- filter(abmeta, isotype == "IgG1", visit!=8)
table(ig1$antigen)
```
```{r}
ggplot(ig1) +
  aes(MFI, antigen, col=infancy_vac) +
  geom_boxplot() + 
  facet_wrap(vars(visit), nrow=2)
```
```{r}
ggplot(filter(ig1, antigen=="FIM2/3")) +
aes(MFI, col=infancy_vac) +
geom_boxplot() +
facet_wrap(vars(visit)) +
theme_bw()
```
```{r}
url <- "https://www.cmi-pb.org/api/v2/rnaseq?versioned_ensembl_gene_id=eq.ENSG00000211896.7"

rna <- read_json(url, simplifyVector = TRUE) 
```

```{r}
ssrna <- inner_join(rna,meta)
```

```{r}
ggplot(ssrna) +
  aes(visit, tpm, group=subject_id) +
  geom_point() +
  geom_line(alpha=0.2)
```

