---
title: "lab06"
author: Eva Zhang
format: html
editor: visual
---

## Functions in R

```{r}
# Example input vectors to start with
student1 <- c(100, 100, 100, 100, 100, 100, 100, 90)
student2 <- c(100, NA, 90, 90, 90, 90, 97, 80)
student3 <- c(90, NA, NA, NA, NA, NA, NA, NA)
```

```{r}
# removes elements based on the index [-idx]
mean(student1[-which.min(student1)])
mean(student2[-which.min(student2)],na.rm=T)
mean(student3[-which.min(student3)],na.rm=T)
student3[is.na(student3)] <- 0 # assign 0 value to all the NAs
student3
```

```{r}
grade <- function(x) {
  x[is.na(x)] <- 0
  mean(x[-which.min(x)])
}
```

```{r}
# test the function 
grade(student2)
```

```{r}
# import the gradebook CSV file
url <- "https://tinyurl.com/gradeinput" # make the first column as row names 
gradebook <- read.csv(url, row.names=1)
head(gradebook)
```

```{r}
# 1 means applying the function over rows
results <- apply(gradebook, 1, grade)
results
```

```{r}
which.max(results)
```

```{r}
mask <- gradebook # create a copy of the gradebook
mask[is.na(mask)] <- 0
mask
```

```{r}
which.min(apply(mask, 2, mean))
```

```{r}
boxplot(gradebook)
```

> Q4

```{r}
cor(mask$hw5,results)
```

```{r}
apply(mask, 2, cor, results)
```



## HW6

```{r}
library(bio3d) 
#' Title
#'
#' @param x 
#' @param chain_name 
#' @param elety_name 
#' @param yl 
#' @param atom_col 
#'
#' @return
#' @export
#'
#' @examples
#' 
prostr <- function(x, chain_name = "A", elety_name = "CA", yl = "Bfactor", atom_col = "b"){
  s <- read.pdb(x)
  s.chain <- trim.pdb(s, chain = chain_name, elety = elety_name)
  s.atom <- s.chain$atom[,atom_col]
  plotb3(s.atom, sse=s.chain, typ="l", ylab = yl)
}
prostr("4AKE")
```
```{r}
plot_Bfactor <- function(x){
# read a Protein Data Bank file
s <- read.pdb(x)
# trim PDB object
s.chainA <- trim.pdb(s, chain="A", elety="CA")
# obtain b-factor values
s.b <- s.chainA$atom$b
# plot the trend of B-factor
plotb3(s.b, sse=s.chainA, typ="l", ylab="Bfactor")
}

plot_Bfactor("4AKE")
```

