---
title: "lab08"
format: html
editor: visual
---

```{r}
fna.data <- "https://bioboot.github.io/bimm143_S20/class-material/WisconsinCancer.csv"
wisc.df <- read.csv(fna.data, row.names=1)
head(wisc.df)
```

```{r}
dim(wisc.df)
table(wisc.df$diagnosis)["B"]
grep("_mean",colnames(wisc.df))
length(grep("_mean",colnames(wisc.df)))
grep("_mean",colnames(wisc.df),value=T)
colnames(wisc.df)[grep("_mean",colnames(wisc.df))]
```

```{r}
wisc.data <- wisc.df[,-1]
#factors are usually for catagorical data
diagnosis <- as.factor(wisc.df$diagnosis) 
```

```{r}
colMeans(wisc.data)
head(sort(round(apply(wisc.data,2,sd),2),decreasing=T))
```

```{r}
wisc.pr <- prcomp(wisc.data,scale=T )
summary(wisc.pr)
```

```{r}
attributes(wisc.pr)
```

```{r}
pr.var <- wisc.pr$sdev^2
pve <- pr.var/sum(pr.var)
plot(pve,type='o')
```

```{r}
library(ggplot2)

pc <- as.data.frame(wisc.pr$x)
ggplot(pc) +
  aes(PC1,PC2,col=diagnosis) +
  geom_point()
```

```{r}
data.dist <- dist(scale(wisc.data))
hc <- hclust(data.dist)
plot(hc)
abline(h=19,col="red")
```

```{r}
grps <- cutree(hc,h=19)
table(grps)
```

```{r}
hc2 <- hclust(dist(wisc.pr$x[,1:3]),method="ward.D2")
plot(hc2)
```

```{r}
grps2 <- cutree(hc2,k=2)
table(grps2,diagnosis)
```
